Grails2.5: Fix binding of empty datePicker values (also for save)
Re-apply fix done to update() in 457de2d7 also to save():

Grails 2.3 replaced the data binder: https://grails.github.io/grails2-doc/2.5.x/guide/upgradingFrom22.html

This broke storing of an empty datePicker selection - the new binder tries to map the empty value to a date and fails with:
    java.lang.AssertionError: Can't populate a date without a year. Expression: fieldValues.containsProperty(prefix.plus(year))

Fix by manually handling the binding/clearing of accountExpires.